spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexsplit?useSSL=false&serverTimezone=UTC
    username: root
    password: Viraj@2002
  jpa:
    hibernate:
      ddl-auto: none # Managed by Flyway
  flyway:
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
server:
  port: 8080
jwt:
  secret: X7k9pL2mQ4jR8vT6yB3nF1cD5hG9jL4kP8mQ2vT6yB3nF1cD5h
  expiration: 60
logging:
  file:
    name: logs/nexsplit.log
  level:
    com.nexsplit: DEBUG
    org.springframework.security: DEBUG