spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexsplit
    username: postgres
    password: Viraj@2002
  #    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Managed by Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

server:
  port: 8080

jwt:
  secret: X7k9pL2mQ4jR8vT6yB3nF1cD5hG9jL4kP8mQ2vT6yB3nF1cD5h
  expiration: 60

logging:
  file:
    name: logs/nexsplit.log
  level:
    com.nexsplit: DEBUG
    org.springframework.security: DEBUG
#security:
#  cors:
#    allow-credentials: true
#    allowed-origins:
#      - http://localhost:3000
#      - http://127.0.0.1:3000
#    allowed-methods:
#      - GET
#      - POST
#      - PUT
#      - PATCH
#      - DELETE
#      - OPTIONS
#    allowed-headers:
#      - Authorization
#      - Origin
#      - Content-Type
#      - Accept
#      - Accept-Encoding
#      - Accept-Language
#      - Access-Control-Allow-Origin
#      - Access-Control-Allow-Headers
#      - Access-Control-Request-Method
#      - X-Requested-With
#      - X-Auth-Token
#      - X-Xsrf-Token
#      - Cache-Control
#      - Id-Token
